Repository reactiverse/es4x, pull requests merged in 2020-10, with the labels that each got.

#413 Added Russian documentation
  docs/ru/README.md
  docs/ru/advanced/README.md
  docs/ru/advanced/commonjs.md
  docs/ru/advanced/esm.md
  docs/ru/advanced/globals.md
  docs/ru/advanced/jars.md
  docs/ru/advanced/logging.md
  docs/ru/advanced/security.md
  docs/ru/advanced/vertx.md
  docs/ru/advanced/worker.md
  docs/ru/api/README.md
  docs/ru/examples/README.md
  docs/ru/examples/hello-world/index.js
  docs/ru/examples/hello-world/package.json
  docs/ru/examples/postgresql/index.js
  docs/ru/examples/postgresql/package.json
  docs/ru/examples/web-application/index.js
  docs/ru/examples/web-application/package.json
  docs/ru/get-started/README.md
  docs/ru/get-started/contributing.md
  docs/ru/get-started/debug.md
  docs/ru/get-started/hello-world.md
  docs/ru/get-started/install.md
  docs/ru/get-started/license.md
  docs/ru/get-started/package.md
  docs/ru/get-started/res/debug.png
  docs/ru/get-started/res/es4x-ts.gif
  docs/ru/get-started/res/round-18-js.png
  docs/ru/get-started/res/round-18.png
  docs/ru/get-started/res/vscode-debug.png
  docs/ru/get-started/run.md
  docs/ru/get-started/shell.md
  docs/ru/get-started/test.md
Labels: Hacktoberfest, hacktoberfest-accepted

#416 Added docs translation in polish
  docs/pl/README.md
  docs/pl/advanced/README.md
  docs/pl/advanced/commonjs.md
  docs/pl/advanced/esm.md
  docs/pl/advanced/globals.md
  docs/pl/advanced/jars.md
  docs/pl/advanced/logging.md
  docs/pl/advanced/security.md
  docs/pl/advanced/vertx.md
  docs/pl/advanced/worker.md
  docs/pl/api/README.md
  docs/pl/examples/README.md
  docs/pl/examples/hello-world/index.js
  docs/pl/examples/hello-world/package.json
  docs/pl/examples/postgresql/index.js
  docs/pl/examples/postgresql/package.json
  docs/pl/examples/web-application/index.js
  docs/pl/examples/web-application/package.json
  docs/pl/get-started/README.md
  docs/pl/get-started/contributing.md
  docs/pl/get-started/debug.md
  docs/pl/get-started/hello-world.md
  docs/pl/get-started/install.md
  docs/pl/get-started/license.md
  docs/pl/get-started/package.md
  docs/pl/get-started/res/debug.png
  docs/pl/get-started/res/es4x-ts.gif
  docs/pl/get-started/res/round-18-js.png
  docs/pl/get-started/res/round-18.png
  docs/pl/get-started/res/vscode-debug.png
  docs/pl/get-started/run.md
  docs/pl/get-started/shell.md
  docs/pl/get-started/test.md
  docs/pl/images/logo.svg
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#414 Docs/gr
  docs/gr/api/README.md
  docs/gr/get-started/contributing.md
  docs/gr/get-started/license.md
  docs/gr/get-started/package.md
  docs/gr/get-started/res/debug.png
  docs/gr/get-started/res/es4x-ts.gif
  docs/gr/get-started/res/round-18-js.png
  docs/gr/get-started/res/round-18.png
  docs/gr/get-started/res/vscode-debug.png
  docs/gr/get-started/run.md
  docs/gr/get-started/shell.md
  docs/gr/get-started/test.md
Labels: Hacktoberfest, hacktoberfest-accepted

#411 Docs/gr
  docs/gr/README.md
  docs/gr/advanced/README.md
  docs/gr/advanced/commonjs.md
  docs/gr/advanced/esm.md
  docs/gr/advanced/globals.md
  docs/gr/advanced/jars.md
  docs/gr/advanced/logging.md
  docs/gr/advanced/security.md
  docs/gr/advanced/vertx.md
  docs/gr/advanced/worker.md
  docs/gr/get-started/README.md
  docs/gr/get-started/debug.md
  docs/gr/get-started/hello-world.md
  docs/gr/get-started/install.md
Labels: Hacktoberfest, hacktoberfest-accepted

#418 Translated config labels
  docs/.vuepress/config.js
Labels: Hacktoberfest, hacktoberfest-accepted

#420 Labels translated to Russian
  docs/.vuepress/config.js
Labels: Hacktoberfest, hacktoberfest-accepted

#422 Added and translated the examples directory
  docs/gr/examples/README.md
  docs/gr/examples/hello-world/index.js
  docs/gr/examples/hello-world/package.json
  docs/gr/examples/postgresql/index.js
  docs/gr/examples/postgresql/package.json
  docs/gr/examples/web-application/index.js
  docs/gr/examples/web-application/package.json
Labels: Hacktoberfest, hacktoberfest-accepted

#419 Update labels for polish translation in config.js
  docs/.vuepress/config.js
Labels: Hacktoberfest, hacktoberfest-accepted

#424 Partial Spanish Translation issue #404
  docs/.vuepress/config.js
  docs/es/README.md
  docs/es/advanced/README.md
  docs/es/advanced/commonjs.md
  docs/es/advanced/esm.md
  docs/es/advanced/globals.md
  docs/es/advanced/jars.md
  docs/es/advanced/logging.md
  docs/es/advanced/security.md
  docs/es/advanced/vertx.md
  docs/es/advanced/worker.md
  docs/es/api/README.md
  docs/es/examples/README.md
  docs/es/examples/hello-world/index.js
  docs/es/examples/hello-world/package.json
  docs/es/examples/postgresql/index.js
  docs/es/examples/postgresql/package.json
  docs/es/examples/web-application/index.js
  docs/es/examples/web-application/package.json
  docs/es/get-started/README.md
  docs/es/get-started/contributing.md
  docs/es/get-started/debug.md
  docs/es/get-started/hello-world.md
  docs/es/get-started/install.md
  docs/es/get-started/license.md
  docs/es/get-started/package.md
  docs/es/get-started/res/debug.png
  docs/es/get-started/res/es4x-ts.gif
  docs/es/get-started/res/round-18-js.png
  docs/es/get-started/res/round-18.png
  docs/es/get-started/res/vscode-debug.png
  docs/es/get-started/run.md
  docs/es/get-started/shell.md
  docs/es/get-started/test.md
  docs/es/images/logo.svg
Labels: Hacktoberfest, hacktoberfest-accepted, in progress
